---
name: CI
on:
  pull_request:
    branches: [main]
env:
  BUILDER_BASE_IMAGE: maven
  BUILDER_BASE_IMAGE_REGISTRY: docker.io
  BUILDER_BASE_IMAGE_REGISTRY_PATH: library
  # Google Artifact Registry Example:
  # BUILDER_BASE_IMAGE_REGISTRY: us-docker.pkg.dev
  # BUILDER_BASE_IMAGE_REGISTRY_PATH: $PROJECT_ID/$PATH
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-env:
          - dev
          - test
          - prod
        maven-vsn:
          - 3.8.6
        maven-jdk-vsn:
          - 18
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          driver: docker
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v3
        id: cache
        with:
          # Cache deps, build, and package mgr dirs
          path: |
            .m2
            target

          # Cache based on OS, BUILD_ENV, LANG, LANG_VSN, and hashFiles('**/lang.lock')
          # The default branch should cache the same without the hash for a restore
          # from latest merge to the default branch
          key: |
            ${{ matrix.app-env }}-${{ matrix.maven-vsn }}-${{ matrix.maven-jdk-vsn }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ matrix.app-env }}-${{ matrix.maven-vsn }}-${{ matrix.maven-jdk-vsn }}
      - name: Build the Docker image
        run: |
          docker build . \
            --tag ghcr.io/${{ github.repository }}/container-dev-builder:${{ matrix.app-env }}-${{ matrix.maven-vsn }}-${{ matrix.maven-jdk-vsn }}-${{ github.sha }} \
            --target builder \
            --build-arg BUILDER_REGISTRY=${{ env.BUILDER_BASE_IMAGE_REGISTRY }} \
            --build-arg BUILDER_REGISTRY_PATH=${{ env.BUILDER_BASE_IMAGE_REGISTRY_PATH }} \
            --build-arg BUILDER_BASE_IMAGE=${{ env.BUILDER_BASE_IMAGE }} \
            --build-arg BUILDER_BASE_IMAGE_TAG=${{ matrix.maven-vsn }}-eclipse-temurin-${{ matrix.maven-jdk-vsn }}-alpine \
            --build-arg APP_ENV=${{ matrix.app-env }}
      - name: Copy Docker Contents to Host
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker run --rm --entrypoint sh ghcr.io/${{ github.repository }}/container-dev-builder:${{ matrix.app-env }}-${{ matrix.maven-vsn }}-${{ matrix.maven-jdk-vsn }}-${{ github.sha }} ls -al
          docker container create --name cache ghcr.io/${{ github.repository }}/container-dev-builder:${{ matrix.app-env }}-${{ matrix.maven-vsn }}-${{ matrix.maven-jdk-vsn }}-${{ github.sha }}
          docker container cp cache:/opt/app/target .
          docker container cp cache:/opt/app/.m2 .
  check-formatted:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        app-env:
          - dev
        maven-vsn:
          - 3.8.6
        maven-jdk-vsn:
          - 18
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |-
          docker container run ghcr.io/${{ github.repository }}/container-dev-builder:${{ matrix.app-env }}-${{ matrix.maven-vsn }}-${{ matrix.maven-jdk-vsn }}-${{ github.sha }} yamllint . --strict --format github
  unit-test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        app-env:
          - test
        maven-vsn:
          - 3.8.6
        maven-jdk-vsn:
          - 18
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |-
          docker container run ghcr.io/${{ github.repository }}/container-dev-builder:${{ matrix.app-env }}-${{ matrix.maven-vsn }}-${{ matrix.maven-jdk-vsn }}-${{ github.sha }} mvn test -o -P $MAVEN_PROFILES -f /opt/app/pom.xml
